[package]
name = "tcp-request"
version = "1.5.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """A Rust library for sending raw TCP requests, with features for handling responses, managing redirects, and working with compressed data over TCP connections."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/tcp-request.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",    
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
http-type = "2.21.0"
lombok-macros = "1.5.0"

[dev-dependencies]
color-output = "6.1.4"

[profile.dev]
incremental = true
opt-level = 3
lto = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
